apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-cli
  template:
    metadata:
      labels:
        app: pizza-cli
    spec:
      containers:
        - name: pizzacli
          image: registry.patrick.dev.br/library/pizza-cli:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pizzacli-svc
spec:
  selector:
    app: pizza-cli
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pizzacli-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: patrick.dev.br
      http:
        paths:
          - path: /pizza-cli
            pathType: Prefix
            backend:
              service:
                name: pizzacli-svc
                port:
                  number: 3000